Improved the content in HTML
Aniruddha-Shriwant/TinDog pull request #1
Opened 2020-10-01 16:03 UTC by prajaktaPh

2020-10-01 16:39 UTC, Aniruddha-Shriwant requested changes

2020-10-01 16:39 UTC, Aniruddha-Shriwant commented on index.html
> +                <h3 class="features_h3">Guaranteed to work in par casesm.</h3>
What's this per "casesm" ?

2020-10-03 09:00 UTC, OmkarPh commented on index.html
> +                <h3 class="features_h3">Guaranteed to work in par casesm.</h3>
I forgot 🙃 Maybe some typo 😁

2020-10-03 12:53 UTC, prajaktaPh commented
Isko approve kar ke close kar de :-)

2020-10-03 12:53 UTC, prajaktaPh commented
merge mat kar chalega haha

2020-10-03 19:02 UTC, Aniruddha-Shriwant approved these changes

2020-10-03 19:06 UTC, merged